{% set name = "esa-climate-toolbox" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esa-cci/esa-climate-toolbox/archive/v{{ version }}.tar.gz
  sha256: 2f10b21e34e8999bc9ed9d94b65f476bdcba0fcf9794849b5ca427239bfc3dc2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    # Required
    - aiohttp >=3.6
    - lxml >=4.5
    - nest-asyncio >=1.3
    - pydap ==3.3
    - xcube >=1.3.0

test:
  imports:
    - esa_climate_toolbox

about:
  home: https://github.com/esa-cci/esa-climate-toolbox
  summary: 'A python package to provide access to CCI data from the ESA Open Data Portal'
  description: |
    The ESA CCI Toolbox is designed to provide access to CCI data
    from the ESA Open Data Portal.
    Also, it contains functions to operate on this data.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/esa-cci/esa-climate-toolbox

extra:
  recipe-maintainers:
    - TonioF
