{% set name = "esa-climate-toolbox" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esa-cci/esa-climate-toolbox/archive/v{{ version }}.tar.gz
  sha256: e23b7f2083debaa0538f6f0bba818da11fdab028e2eebcd376e03cd373df3682

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    # Required
    - aiohttp >=3.6
    - lxml >=4.5
    - nest-asyncio >=1.3
    - pydap ==3.3
    - xcube >=1.4.0

test:
  imports:
    - esa_climate_toolbox

about:
  home: https://github.com/esa-cci/esa-climate-toolbox
  summary: 'A python package to provide access to CCI data from the ESA Open Data Portal'
  description: |
    The ESA CCI Toolbox is designed to provide access to CCI data
    from the ESA Open Data Portal.
    Also, it contains functions to operate on this data.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/esa-cci/esa-climate-toolbox

extra:
  recipe-maintainers:
    - TonioF
    - pont-us
    - TejasMorbagal
    - forman
    - AliceBalfanz
    - thomasstorm
    - ruchimotwaniBC
