{% set python_min = "3.10" %}
{% set name = "esa-climate-toolbox" %}
{% set version = "1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esa-cci/esa-climate-toolbox/archive/v{{ version }}.tar.gz
  sha256: 2e2b996c9f2d62691b3333435eb04c87d8427bc596337515888715e572b2e568

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    # Required
    - cartopy
    - cftime
    - dask
    - geopandas >=0.14
    - matplotlib-base
    - numba >0.35
    - numcodecs
    - numpy
    - pandas
    - pyproj
    - python-dateutil
    - shapely
    - simplekml
    - six
    - xarray
    - xcube >=1.8.0
    - xcube-cci >=0.11.1
    - zarr <3

test:
  requires:
    - python {{ python_min }}
  imports:
    - esa_climate_toolbox

about:
  home: https://github.com/esa-cci/esa-climate-toolbox
  summary: 'A python package to provide access to CCI data from the ESA Open Data Portal'
  description: |
    The ESA CCI Toolbox is designed to provide access to CCI data
    from the ESA Open Data Portal.
    Also, it contains functions to operate on this data.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/esa-cci/esa-climate-toolbox

extra:
  recipe-maintainers:
    - TonioF
    - pont-us
    - TejasMorbagal
    - forman
    - AliceBalfanz
    - thomasstorm
    - konstntokas
    - b-yogesh
    - clarasb
